[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "untangled_snakes"
authors = [
    {name = "Paul Haerle", email = "hello@phaer.org"},
]
description = "Experiments with python resolving"
requires-python = ">=3.10"

dependencies = [
    "resolvelib",
    "packaging",
    "build",
    "requests",
    "rich",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
     "pytest",
     "requests-mock",
]


[project.scripts]
untangled_snakes = "untangled_snakes:main"
